{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "8cfd34f4",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import random\n",
    "import seaborn as sn\n",
    "from sklearn.utils import shuffle\n",
    "import numpy as np\n",
    "import preprocessor\n",
    "from sklearn.pipeline import Pipeline\n",
    "from sklearn.feature_extraction.text import CountVectorizer\n",
    "from sklearn.naive_bayes import MultinomialNB\n",
    "from sklearn.metrics import classification_report, plot_confusion_matrix\n",
    "from matplotlib import pyplot as plt\n",
    "from sklearn.pipeline import Pipeline\n",
    "from sklearn.feature_extraction.text import CountVectorizer\n",
    "from sklearn.dummy import DummyClassifier\n",
    "\n",
    "from Utilities import * "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d2de6053",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "4833e7c8",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\alejo\\AppData\\Local\\Temp/ipykernel_2432/1303396668.py:1: DtypeWarning: Columns (4,5,6,12,13,16) have mixed types.Specify dtype option on import or set low_memory=False.\n",
      "  genuine_sample, ssb2, ssb3 = generate_data()\n",
      "C:\\Users\\alejo\\AppData\\Local\\Temp/ipykernel_2432/1303396668.py:1: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.\n",
      "  genuine_sample, ssb2, ssb3 = generate_data()\n",
      "D:\\TextMiningProject\\Utilities.py:38: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  ssb2[\"Label\"] = [\"bot\" for i in range(len(ssb2))]\n",
      "C:\\Users\\alejo\\AppData\\Local\\Temp/ipykernel_2432/1303396668.py:1: DtypeWarning: Columns (7,10) have mixed types.Specify dtype option on import or set low_memory=False.\n",
      "  genuine_sample, ssb2, ssb3 = generate_data()\n",
      "D:\\TextMiningProject\\Utilities.py:43: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  ssb3[\"Label\"] = [\"bot\" for i in range(len(ssb3))]\n"
     ]
    }
   ],
   "source": [
    "genuine_sample, ssb2, ssb3 = generate_data()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4fff8df5",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "49fdd49a",
   "metadata": {},
   "outputs": [],
   "source": [
    "train_1, train_2, test_1, test_2 = generate_train_test(genuine_sample, ssb2, ssb3)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "6eb0b19b",
   "metadata": {},
   "source": [
    "## Naive Bayes classifier"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "dc63caa5",
   "metadata": {},
   "source": [
    "### SSB_2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "c0880baf",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Pipeline(steps=[('vectorize ', CountVectorizer()), ('MNB', MultinomialNB())])"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "\n",
    "pipe = Pipeline([('vectorize ', CountVectorizer()), ('MNB', MultinomialNB())])\n",
    "pipe.fit(train_1[\"text\"].values.astype('U'), train_1[\"Label\"])\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "a377d32d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "              precision    recall  f1-score   support\n",
      "\n",
      "         bot       0.81      0.81      0.81    128466\n",
      "     genuine       0.89      0.90      0.89    226837\n",
      "\n",
      "    accuracy                           0.86    355303\n",
      "   macro avg       0.85      0.85      0.85    355303\n",
      "weighted avg       0.86      0.86      0.86    355303\n",
      "\n"
     ]
    }
   ],
   "source": [
    "print(classification_report(test_1[\"Label\"], pipe.predict(test_1[\"text\"].values.astype('U'))))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "e2c68615",
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'confusion_matrix' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[1;32m~\\AppData\\Local\\Temp/ipykernel_2432/1854485900.py\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[1;32m----> 1\u001b[1;33m \u001b[0mcm\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mconfusion_matrix\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mtest_1\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;34m\"Label\"\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mpipe\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mpredict\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mtest_1\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;34m\"text\"\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mvalues\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mastype\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m'U'\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m: name 'confusion_matrix' is not defined"
     ]
    }
   ],
   "source": [
    "cm = confusion_matrix(test_1[\"Label\"], pipe.predict(test_1[\"text\"].values.astype('U')))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "54ba323f",
   "metadata": {},
   "outputs": [],
   "source": [
    "def plot_confusion_matrix_custom(cm):\n",
    "    \n",
    "    df_cm = pd.DataFrame(cm, index = [\"bot\", \"genuine\"],\n",
    "                      columns = [\"bot\", \"genuine\"])\n",
    "    plt.figure(figsize = (10,7))\n",
    "    sn.heatmap(df_cm, annot=True,cmap='Blues', fmt='g')\n",
    "    \n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "99cfcef3",
   "metadata": {},
   "outputs": [],
   "source": [
    "plot_confusion_matrix_custom(cm)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "6d9c10cf",
   "metadata": {},
   "source": [
    "### SSB_3"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b63f744b",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "pipe = Pipeline([('vectorize ', CountVectorizer()), ('MNB', MultinomialNB())])\n",
    "pipe.fit(train_1[\"text\"].values.astype('U'), train_1[\"Label\"])\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a784bbf5",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(classification_report(test_2[\"Label\"], pipe.predict(test_2[\"text\"].values.astype('U'))))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0feb9215",
   "metadata": {},
   "outputs": [],
   "source": [
    "cm = confusion_matrix(test_2[\"Label\"], pipe.predict(test_2[\"text\"].values.astype('U')))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e9dea160",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e124daed",
   "metadata": {},
   "outputs": [],
   "source": [
    "plot_confusion_matrix_custom(cm)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "b1a88917",
   "metadata": {},
   "source": [
    "## Baselines"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "cd7bce91",
   "metadata": {},
   "source": [
    "## Dummy Classifier"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "8828b343",
   "metadata": {},
   "source": [
    "## SSB_2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d608a377",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "\n",
    "dummy = Pipeline([('vectorize ', CountVectorizer()), ('dummy', DummyClassifier(strategy = 'stratified'))])\n",
    "\n",
    "dummy.fit(train_1[\"text\"].values.astype('U'), train_1[\"Label\"])\n",
    "\n",
    "print(classification_report(test_1[\"Label\"], dummy.predict(test_1[\"text\"].values.astype('U'))))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1cc5175d",
   "metadata": {},
   "outputs": [],
   "source": [
    "cm = confusion_matrix(test_1[\"Label\"], dummy.predict(test_1[\"text\"].values.astype('U')))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "88ee7fa4",
   "metadata": {},
   "outputs": [],
   "source": [
    "plot_confusion_matrix_custom(cm)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c5218692",
   "metadata": {},
   "source": [
    "## SBB_3"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "39b27f4c",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "\n",
    "dummy = Pipeline([('vectorize ', CountVectorizer()), ('dummy', DummyClassifier(strategy = 'stratified'))])\n",
    "\n",
    "dummy.fit(train_2[\"text\"].values.astype('U'), train_2[\"Label\"])\n",
    "\n",
    "print(classification_report(test_2[\"Label\"], dummy.predict(test_2[\"text\"].values.astype('U'))))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "aff3d9a6",
   "metadata": {},
   "outputs": [],
   "source": [
    "cm = confusion_matrix(test_2[\"Label\"], dummy.predict(test_2[\"text\"].values.astype('U')))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cdc9b69f",
   "metadata": {},
   "outputs": [],
   "source": [
    "plot_confusion_matrix_custom(cm)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "413f6a6f",
   "metadata": {},
   "outputs": [],
   "source": [
    "pd.value_counts(test_1.Label)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "1a4db1b5",
   "metadata": {},
   "source": [
    "## Dummy Classifier"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "14e2bd3a",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\joblib\\memory.py\", line 352, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1202, in fit_transform\n",
      "    vocabulary, X = self._count_vocab(raw_documents,\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1114, in _count_vocab\n",
      "    for feature in analyze(doc):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 99, in _analyze\n",
      "    doc = decoder(doc)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 217, in decode\n",
      "    raise ValueError(\"np.nan is an invalid document, expected byte or \"\n",
      "ValueError: np.nan is an invalid document, expected byte or unicode string.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\joblib\\memory.py\", line 352, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1202, in fit_transform\n",
      "    vocabulary, X = self._count_vocab(raw_documents,\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1114, in _count_vocab\n",
      "    for feature in analyze(doc):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 99, in _analyze\n",
      "    doc = decoder(doc)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 217, in decode\n",
      "    raise ValueError(\"np.nan is an invalid document, expected byte or \"\n",
      "ValueError: np.nan is an invalid document, expected byte or unicode string.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\joblib\\memory.py\", line 352, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1202, in fit_transform\n",
      "    vocabulary, X = self._count_vocab(raw_documents,\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1114, in _count_vocab\n",
      "    for feature in analyze(doc):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 99, in _analyze\n",
      "    doc = decoder(doc)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 217, in decode\n",
      "    raise ValueError(\"np.nan is an invalid document, expected byte or \"\n",
      "ValueError: np.nan is an invalid document, expected byte or unicode string.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\joblib\\memory.py\", line 352, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1202, in fit_transform\n",
      "    vocabulary, X = self._count_vocab(raw_documents,\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1114, in _count_vocab\n",
      "    for feature in analyze(doc):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 99, in _analyze\n",
      "    doc = decoder(doc)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 217, in decode\n",
      "    raise ValueError(\"np.nan is an invalid document, expected byte or \"\n",
      "ValueError: np.nan is an invalid document, expected byte or unicode string.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\joblib\\memory.py\", line 352, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1202, in fit_transform\n",
      "    vocabulary, X = self._count_vocab(raw_documents,\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1114, in _count_vocab\n",
      "    for feature in analyze(doc):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 99, in _analyze\n",
      "    doc = decoder(doc)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 217, in decode\n",
      "    raise ValueError(\"np.nan is an invalid document, expected byte or \"\n",
      "ValueError: np.nan is an invalid document, expected byte or unicode string.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\joblib\\memory.py\", line 352, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1202, in fit_transform\n",
      "    vocabulary, X = self._count_vocab(raw_documents,\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1114, in _count_vocab\n",
      "    for feature in analyze(doc):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 99, in _analyze\n",
      "    doc = decoder(doc)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 217, in decode\n",
      "    raise ValueError(\"np.nan is an invalid document, expected byte or \"\n",
      "ValueError: np.nan is an invalid document, expected byte or unicode string.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\joblib\\memory.py\", line 352, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1202, in fit_transform\n",
      "    vocabulary, X = self._count_vocab(raw_documents,\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1114, in _count_vocab\n",
      "    for feature in analyze(doc):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 99, in _analyze\n",
      "    doc = decoder(doc)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 217, in decode\n",
      "    raise ValueError(\"np.nan is an invalid document, expected byte or \"\n",
      "ValueError: np.nan is an invalid document, expected byte or unicode string.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\joblib\\memory.py\", line 352, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1202, in fit_transform\n",
      "    vocabulary, X = self._count_vocab(raw_documents,\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1114, in _count_vocab\n",
      "    for feature in analyze(doc):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 99, in _analyze\n",
      "    doc = decoder(doc)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 217, in decode\n",
      "    raise ValueError(\"np.nan is an invalid document, expected byte or \"\n",
      "ValueError: np.nan is an invalid document, expected byte or unicode string.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\joblib\\memory.py\", line 352, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1202, in fit_transform\n",
      "    vocabulary, X = self._count_vocab(raw_documents,\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1114, in _count_vocab\n",
      "    for feature in analyze(doc):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 99, in _analyze\n",
      "    doc = decoder(doc)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 217, in decode\n",
      "    raise ValueError(\"np.nan is an invalid document, expected byte or \"\n",
      "ValueError: np.nan is an invalid document, expected byte or unicode string.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\joblib\\memory.py\", line 352, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1202, in fit_transform\n",
      "    vocabulary, X = self._count_vocab(raw_documents,\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1114, in _count_vocab\n",
      "    for feature in analyze(doc):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 99, in _analyze\n",
      "    doc = decoder(doc)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 217, in decode\n",
      "    raise ValueError(\"np.nan is an invalid document, expected byte or \"\n",
      "ValueError: np.nan is an invalid document, expected byte or unicode string.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\joblib\\memory.py\", line 352, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1202, in fit_transform\n",
      "    vocabulary, X = self._count_vocab(raw_documents,\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1114, in _count_vocab\n",
      "    for feature in analyze(doc):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 99, in _analyze\n",
      "    doc = decoder(doc)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 217, in decode\n",
      "    raise ValueError(\"np.nan is an invalid document, expected byte or \"\n",
      "ValueError: np.nan is an invalid document, expected byte or unicode string.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\joblib\\memory.py\", line 352, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1202, in fit_transform\n",
      "    vocabulary, X = self._count_vocab(raw_documents,\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1114, in _count_vocab\n",
      "    for feature in analyze(doc):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 99, in _analyze\n",
      "    doc = decoder(doc)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 217, in decode\n",
      "    raise ValueError(\"np.nan is an invalid document, expected byte or \"\n",
      "ValueError: np.nan is an invalid document, expected byte or unicode string.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\joblib\\memory.py\", line 352, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1202, in fit_transform\n",
      "    vocabulary, X = self._count_vocab(raw_documents,\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1114, in _count_vocab\n",
      "    for feature in analyze(doc):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 99, in _analyze\n",
      "    doc = decoder(doc)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 217, in decode\n",
      "    raise ValueError(\"np.nan is an invalid document, expected byte or \"\n",
      "ValueError: np.nan is an invalid document, expected byte or unicode string.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\joblib\\memory.py\", line 352, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1202, in fit_transform\n",
      "    vocabulary, X = self._count_vocab(raw_documents,\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1114, in _count_vocab\n",
      "    for feature in analyze(doc):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 99, in _analyze\n",
      "    doc = decoder(doc)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 217, in decode\n",
      "    raise ValueError(\"np.nan is an invalid document, expected byte or \"\n",
      "ValueError: np.nan is an invalid document, expected byte or unicode string.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\joblib\\memory.py\", line 352, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1202, in fit_transform\n",
      "    vocabulary, X = self._count_vocab(raw_documents,\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1114, in _count_vocab\n",
      "    for feature in analyze(doc):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 99, in _analyze\n",
      "    doc = decoder(doc)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 217, in decode\n",
      "    raise ValueError(\"np.nan is an invalid document, expected byte or \"\n",
      "ValueError: np.nan is an invalid document, expected byte or unicode string.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\joblib\\memory.py\", line 352, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1202, in fit_transform\n",
      "    vocabulary, X = self._count_vocab(raw_documents,\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1114, in _count_vocab\n",
      "    for feature in analyze(doc):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 99, in _analyze\n",
      "    doc = decoder(doc)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 217, in decode\n",
      "    raise ValueError(\"np.nan is an invalid document, expected byte or \"\n",
      "ValueError: np.nan is an invalid document, expected byte or unicode string.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\joblib\\memory.py\", line 352, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1202, in fit_transform\n",
      "    vocabulary, X = self._count_vocab(raw_documents,\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1114, in _count_vocab\n",
      "    for feature in analyze(doc):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 99, in _analyze\n",
      "    doc = decoder(doc)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 217, in decode\n",
      "    raise ValueError(\"np.nan is an invalid document, expected byte or \"\n",
      "ValueError: np.nan is an invalid document, expected byte or unicode string.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\joblib\\memory.py\", line 352, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1202, in fit_transform\n",
      "    vocabulary, X = self._count_vocab(raw_documents,\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1114, in _count_vocab\n",
      "    for feature in analyze(doc):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 99, in _analyze\n",
      "    doc = decoder(doc)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 217, in decode\n",
      "    raise ValueError(\"np.nan is an invalid document, expected byte or \"\n",
      "ValueError: np.nan is an invalid document, expected byte or unicode string.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\joblib\\memory.py\", line 352, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1202, in fit_transform\n",
      "    vocabulary, X = self._count_vocab(raw_documents,\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1114, in _count_vocab\n",
      "    for feature in analyze(doc):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 99, in _analyze\n",
      "    doc = decoder(doc)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 217, in decode\n",
      "    raise ValueError(\"np.nan is an invalid document, expected byte or \"\n",
      "ValueError: np.nan is an invalid document, expected byte or unicode string.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\joblib\\memory.py\", line 352, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1202, in fit_transform\n",
      "    vocabulary, X = self._count_vocab(raw_documents,\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1114, in _count_vocab\n",
      "    for feature in analyze(doc):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 99, in _analyze\n",
      "    doc = decoder(doc)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 217, in decode\n",
      "    raise ValueError(\"np.nan is an invalid document, expected byte or \"\n",
      "ValueError: np.nan is an invalid document, expected byte or unicode string.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\joblib\\memory.py\", line 352, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1202, in fit_transform\n",
      "    vocabulary, X = self._count_vocab(raw_documents,\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1114, in _count_vocab\n",
      "    for feature in analyze(doc):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 99, in _analyze\n",
      "    doc = decoder(doc)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 217, in decode\n",
      "    raise ValueError(\"np.nan is an invalid document, expected byte or \"\n",
      "ValueError: np.nan is an invalid document, expected byte or unicode string.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\joblib\\memory.py\", line 352, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1202, in fit_transform\n",
      "    vocabulary, X = self._count_vocab(raw_documents,\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1114, in _count_vocab\n",
      "    for feature in analyze(doc):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 99, in _analyze\n",
      "    doc = decoder(doc)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 217, in decode\n",
      "    raise ValueError(\"np.nan is an invalid document, expected byte or \"\n",
      "ValueError: np.nan is an invalid document, expected byte or unicode string.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\joblib\\memory.py\", line 352, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1202, in fit_transform\n",
      "    vocabulary, X = self._count_vocab(raw_documents,\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1114, in _count_vocab\n",
      "    for feature in analyze(doc):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 99, in _analyze\n",
      "    doc = decoder(doc)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 217, in decode\n",
      "    raise ValueError(\"np.nan is an invalid document, expected byte or \"\n",
      "ValueError: np.nan is an invalid document, expected byte or unicode string.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\joblib\\memory.py\", line 352, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1202, in fit_transform\n",
      "    vocabulary, X = self._count_vocab(raw_documents,\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1114, in _count_vocab\n",
      "    for feature in analyze(doc):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 99, in _analyze\n",
      "    doc = decoder(doc)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 217, in decode\n",
      "    raise ValueError(\"np.nan is an invalid document, expected byte or \"\n",
      "ValueError: np.nan is an invalid document, expected byte or unicode string.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\joblib\\memory.py\", line 352, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1202, in fit_transform\n",
      "    vocabulary, X = self._count_vocab(raw_documents,\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1114, in _count_vocab\n",
      "    for feature in analyze(doc):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 99, in _analyze\n",
      "    doc = decoder(doc)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 217, in decode\n",
      "    raise ValueError(\"np.nan is an invalid document, expected byte or \"\n",
      "ValueError: np.nan is an invalid document, expected byte or unicode string.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\joblib\\memory.py\", line 352, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1202, in fit_transform\n",
      "    vocabulary, X = self._count_vocab(raw_documents,\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1114, in _count_vocab\n",
      "    for feature in analyze(doc):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 99, in _analyze\n",
      "    doc = decoder(doc)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 217, in decode\n",
      "    raise ValueError(\"np.nan is an invalid document, expected byte or \"\n",
      "ValueError: np.nan is an invalid document, expected byte or unicode string.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\joblib\\memory.py\", line 352, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1202, in fit_transform\n",
      "    vocabulary, X = self._count_vocab(raw_documents,\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1114, in _count_vocab\n",
      "    for feature in analyze(doc):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 99, in _analyze\n",
      "    doc = decoder(doc)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 217, in decode\n",
      "    raise ValueError(\"np.nan is an invalid document, expected byte or \"\n",
      "ValueError: np.nan is an invalid document, expected byte or unicode string.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\joblib\\memory.py\", line 352, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1202, in fit_transform\n",
      "    vocabulary, X = self._count_vocab(raw_documents,\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1114, in _count_vocab\n",
      "    for feature in analyze(doc):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 99, in _analyze\n",
      "    doc = decoder(doc)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 217, in decode\n",
      "    raise ValueError(\"np.nan is an invalid document, expected byte or \"\n",
      "ValueError: np.nan is an invalid document, expected byte or unicode string.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\joblib\\memory.py\", line 352, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1202, in fit_transform\n",
      "    vocabulary, X = self._count_vocab(raw_documents,\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1114, in _count_vocab\n",
      "    for feature in analyze(doc):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 99, in _analyze\n",
      "    doc = decoder(doc)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 217, in decode\n",
      "    raise ValueError(\"np.nan is an invalid document, expected byte or \"\n",
      "ValueError: np.nan is an invalid document, expected byte or unicode string.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\joblib\\memory.py\", line 352, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1202, in fit_transform\n",
      "    vocabulary, X = self._count_vocab(raw_documents,\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1114, in _count_vocab\n",
      "    for feature in analyze(doc):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 99, in _analyze\n",
      "    doc = decoder(doc)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 217, in decode\n",
      "    raise ValueError(\"np.nan is an invalid document, expected byte or \"\n",
      "ValueError: np.nan is an invalid document, expected byte or unicode string.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\joblib\\memory.py\", line 352, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1202, in fit_transform\n",
      "    vocabulary, X = self._count_vocab(raw_documents,\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1114, in _count_vocab\n",
      "    for feature in analyze(doc):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 99, in _analyze\n",
      "    doc = decoder(doc)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 217, in decode\n",
      "    raise ValueError(\"np.nan is an invalid document, expected byte or \"\n",
      "ValueError: np.nan is an invalid document, expected byte or unicode string.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\joblib\\memory.py\", line 352, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1202, in fit_transform\n",
      "    vocabulary, X = self._count_vocab(raw_documents,\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1114, in _count_vocab\n",
      "    for feature in analyze(doc):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 99, in _analyze\n",
      "    doc = decoder(doc)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 217, in decode\n",
      "    raise ValueError(\"np.nan is an invalid document, expected byte or \"\n",
      "ValueError: np.nan is an invalid document, expected byte or unicode string.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\joblib\\memory.py\", line 352, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1202, in fit_transform\n",
      "    vocabulary, X = self._count_vocab(raw_documents,\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1114, in _count_vocab\n",
      "    for feature in analyze(doc):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 99, in _analyze\n",
      "    doc = decoder(doc)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 217, in decode\n",
      "    raise ValueError(\"np.nan is an invalid document, expected byte or \"\n",
      "ValueError: np.nan is an invalid document, expected byte or unicode string.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\joblib\\memory.py\", line 352, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1202, in fit_transform\n",
      "    vocabulary, X = self._count_vocab(raw_documents,\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1114, in _count_vocab\n",
      "    for feature in analyze(doc):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 99, in _analyze\n",
      "    doc = decoder(doc)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 217, in decode\n",
      "    raise ValueError(\"np.nan is an invalid document, expected byte or \"\n",
      "ValueError: np.nan is an invalid document, expected byte or unicode string.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\joblib\\memory.py\", line 352, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1202, in fit_transform\n",
      "    vocabulary, X = self._count_vocab(raw_documents,\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1114, in _count_vocab\n",
      "    for feature in analyze(doc):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 99, in _analyze\n",
      "    doc = decoder(doc)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 217, in decode\n",
      "    raise ValueError(\"np.nan is an invalid document, expected byte or \"\n",
      "ValueError: np.nan is an invalid document, expected byte or unicode string.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\joblib\\memory.py\", line 352, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1202, in fit_transform\n",
      "    vocabulary, X = self._count_vocab(raw_documents,\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1114, in _count_vocab\n",
      "    for feature in analyze(doc):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 99, in _analyze\n",
      "    doc = decoder(doc)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 217, in decode\n",
      "    raise ValueError(\"np.nan is an invalid document, expected byte or \"\n",
      "ValueError: np.nan is an invalid document, expected byte or unicode string.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\joblib\\memory.py\", line 352, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1202, in fit_transform\n",
      "    vocabulary, X = self._count_vocab(raw_documents,\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1114, in _count_vocab\n",
      "    for feature in analyze(doc):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 99, in _analyze\n",
      "    doc = decoder(doc)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 217, in decode\n",
      "    raise ValueError(\"np.nan is an invalid document, expected byte or \"\n",
      "ValueError: np.nan is an invalid document, expected byte or unicode string.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\joblib\\memory.py\", line 352, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1202, in fit_transform\n",
      "    vocabulary, X = self._count_vocab(raw_documents,\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1114, in _count_vocab\n",
      "    for feature in analyze(doc):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 99, in _analyze\n",
      "    doc = decoder(doc)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 217, in decode\n",
      "    raise ValueError(\"np.nan is an invalid document, expected byte or \"\n",
      "ValueError: np.nan is an invalid document, expected byte or unicode string.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\joblib\\memory.py\", line 352, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1202, in fit_transform\n",
      "    vocabulary, X = self._count_vocab(raw_documents,\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1114, in _count_vocab\n",
      "    for feature in analyze(doc):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 99, in _analyze\n",
      "    doc = decoder(doc)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 217, in decode\n",
      "    raise ValueError(\"np.nan is an invalid document, expected byte or \"\n",
      "ValueError: np.nan is an invalid document, expected byte or unicode string.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 341, in fit\n",
      "    Xt = self._fit(X, y, **fit_params_steps)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 303, in _fit\n",
      "    X, fitted_transformer = fit_transform_one_cached(\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\joblib\\memory.py\", line 352, in __call__\n",
      "    return self.func(*args, **kwargs)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\", line 754, in _fit_transform_one\n",
      "    res = transformer.fit_transform(X, y, **fit_params)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1202, in fit_transform\n",
      "    vocabulary, X = self._count_vocab(raw_documents,\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 1114, in _count_vocab\n",
      "    for feature in analyze(doc):\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 99, in _analyze\n",
      "    doc = decoder(doc)\n",
      "  File \"C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 217, in decode\n",
      "    raise ValueError(\"np.nan is an invalid document, expected byte or \"\n",
      "ValueError: np.nan is an invalid document, expected byte or unicode string.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\alejo\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_search.py:922: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan nan nan nan nan]\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "ename": "ValueError",
     "evalue": "np.nan is an invalid document, expected byte or unicode string.",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "\u001b[1;32m~\\AppData\\Local\\Temp/ipykernel_2432/3707631596.py\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      5\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      6\u001b[0m \u001b[0mclf\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mGridSearchCV\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mpipe\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mparameters\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mscoring\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;34m\"f1_weighted\"\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mcv\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;36m5\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mrefit\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;32mTrue\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 7\u001b[1;33m \u001b[0mclf\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mfit\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mtrain_1\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;34m\"text\"\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mtrain_1\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;34m\"Label\"\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m      8\u001b[0m \u001b[0mprint\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mclassification_report\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mtest_1\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;34m\"Label\"\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mclf\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mpredict\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mtest_1\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;34m\"text\"\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\anaconda3\\lib\\site-packages\\sklearn\\utils\\validation.py\u001b[0m in \u001b[0;36minner_f\u001b[1;34m(*args, **kwargs)\u001b[0m\n\u001b[0;32m     61\u001b[0m             \u001b[0mextra_args\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mlen\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0margs\u001b[0m\u001b[1;33m)\u001b[0m \u001b[1;33m-\u001b[0m \u001b[0mlen\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mall_args\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     62\u001b[0m             \u001b[1;32mif\u001b[0m \u001b[0mextra_args\u001b[0m \u001b[1;33m<=\u001b[0m \u001b[1;36m0\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 63\u001b[1;33m                 \u001b[1;32mreturn\u001b[0m \u001b[0mf\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m*\u001b[0m\u001b[0margs\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     64\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     65\u001b[0m             \u001b[1;31m# extra_args > 0\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_search.py\u001b[0m in \u001b[0;36mfit\u001b[1;34m(self, X, y, groups, **fit_params)\u001b[0m\n\u001b[0;32m    878\u001b[0m             \u001b[0mrefit_start_time\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mtime\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mtime\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    879\u001b[0m             \u001b[1;32mif\u001b[0m \u001b[0my\u001b[0m \u001b[1;32mis\u001b[0m \u001b[1;32mnot\u001b[0m \u001b[1;32mNone\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 880\u001b[1;33m                 \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mbest_estimator_\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mfit\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mX\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0my\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mfit_params\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    881\u001b[0m             \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    882\u001b[0m                 \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mbest_estimator_\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mfit\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mX\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mfit_params\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\u001b[0m in \u001b[0;36mfit\u001b[1;34m(self, X, y, **fit_params)\u001b[0m\n\u001b[0;32m    339\u001b[0m         \"\"\"\n\u001b[0;32m    340\u001b[0m         \u001b[0mfit_params_steps\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_check_fit_params\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m**\u001b[0m\u001b[0mfit_params\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 341\u001b[1;33m         \u001b[0mXt\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_fit\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mX\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0my\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mfit_params_steps\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    342\u001b[0m         with _print_elapsed_time('Pipeline',\n\u001b[0;32m    343\u001b[0m                                  self._log_message(len(self.steps) - 1)):\n",
      "\u001b[1;32m~\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\u001b[0m in \u001b[0;36m_fit\u001b[1;34m(self, X, y, **fit_params_steps)\u001b[0m\n\u001b[0;32m    301\u001b[0m                 \u001b[0mcloned_transformer\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mclone\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mtransformer\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    302\u001b[0m             \u001b[1;31m# Fit or load from cache the current transformer\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 303\u001b[1;33m             X, fitted_transformer = fit_transform_one_cached(\n\u001b[0m\u001b[0;32m    304\u001b[0m                 \u001b[0mcloned_transformer\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mX\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0my\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;32mNone\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    305\u001b[0m                 \u001b[0mmessage_clsname\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;34m'Pipeline'\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\anaconda3\\lib\\site-packages\\joblib\\memory.py\u001b[0m in \u001b[0;36m__call__\u001b[1;34m(self, *args, **kwargs)\u001b[0m\n\u001b[0;32m    350\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    351\u001b[0m     \u001b[1;32mdef\u001b[0m \u001b[0m__call__\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m*\u001b[0m\u001b[0margs\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 352\u001b[1;33m         \u001b[1;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mfunc\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m*\u001b[0m\u001b[0margs\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    353\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    354\u001b[0m     \u001b[1;32mdef\u001b[0m \u001b[0mcall_and_shelve\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m*\u001b[0m\u001b[0margs\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\anaconda3\\lib\\site-packages\\sklearn\\pipeline.py\u001b[0m in \u001b[0;36m_fit_transform_one\u001b[1;34m(transformer, X, y, weight, message_clsname, message, **fit_params)\u001b[0m\n\u001b[0;32m    752\u001b[0m     \u001b[1;32mwith\u001b[0m \u001b[0m_print_elapsed_time\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mmessage_clsname\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mmessage\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    753\u001b[0m         \u001b[1;32mif\u001b[0m \u001b[0mhasattr\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mtransformer\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;34m'fit_transform'\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 754\u001b[1;33m             \u001b[0mres\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mtransformer\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mfit_transform\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mX\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0my\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mfit_params\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    755\u001b[0m         \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    756\u001b[0m             \u001b[0mres\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mtransformer\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mfit\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mX\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0my\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mfit_params\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mtransform\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mX\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\u001b[0m in \u001b[0;36mfit_transform\u001b[1;34m(self, raw_documents, y)\u001b[0m\n\u001b[0;32m   1200\u001b[0m         \u001b[0mmax_features\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mmax_features\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1201\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1202\u001b[1;33m         vocabulary, X = self._count_vocab(raw_documents,\n\u001b[0m\u001b[0;32m   1203\u001b[0m                                           self.fixed_vocabulary_)\n\u001b[0;32m   1204\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\u001b[0m in \u001b[0;36m_count_vocab\u001b[1;34m(self, raw_documents, fixed_vocab)\u001b[0m\n\u001b[0;32m   1112\u001b[0m         \u001b[1;32mfor\u001b[0m \u001b[0mdoc\u001b[0m \u001b[1;32min\u001b[0m \u001b[0mraw_documents\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1113\u001b[0m             \u001b[0mfeature_counter\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;33m{\u001b[0m\u001b[1;33m}\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1114\u001b[1;33m             \u001b[1;32mfor\u001b[0m \u001b[0mfeature\u001b[0m \u001b[1;32min\u001b[0m \u001b[0manalyze\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mdoc\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   1115\u001b[0m                 \u001b[1;32mtry\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1116\u001b[0m                     \u001b[0mfeature_idx\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mvocabulary\u001b[0m\u001b[1;33m[\u001b[0m\u001b[0mfeature\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\u001b[0m in \u001b[0;36m_analyze\u001b[1;34m(doc, analyzer, tokenizer, ngrams, preprocessor, decoder, stop_words)\u001b[0m\n\u001b[0;32m     97\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     98\u001b[0m     \u001b[1;32mif\u001b[0m \u001b[0mdecoder\u001b[0m \u001b[1;32mis\u001b[0m \u001b[1;32mnot\u001b[0m \u001b[1;32mNone\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 99\u001b[1;33m         \u001b[0mdoc\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mdecoder\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mdoc\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    100\u001b[0m     \u001b[1;32mif\u001b[0m \u001b[0manalyzer\u001b[0m \u001b[1;32mis\u001b[0m \u001b[1;32mnot\u001b[0m \u001b[1;32mNone\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    101\u001b[0m         \u001b[0mdoc\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0manalyzer\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mdoc\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\anaconda3\\lib\\site-packages\\sklearn\\feature_extraction\\text.py\u001b[0m in \u001b[0;36mdecode\u001b[1;34m(self, doc)\u001b[0m\n\u001b[0;32m    215\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    216\u001b[0m         \u001b[1;32mif\u001b[0m \u001b[0mdoc\u001b[0m \u001b[1;32mis\u001b[0m \u001b[0mnp\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mnan\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 217\u001b[1;33m             raise ValueError(\"np.nan is an invalid document, expected byte or \"\n\u001b[0m\u001b[0;32m    218\u001b[0m                              \"unicode string.\")\n\u001b[0;32m    219\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mValueError\u001b[0m: np.nan is an invalid document, expected byte or unicode string."
     ]
    }
   ],
   "source": [
    "# how to change scoring? \n",
    "from sklearn.model_selection import GridSearchCV\n",
    "\n",
    "parameters = {'vectorize __binary':(True, False), 'vectorize __ngram_range':[(1,1), (1,2)], \"MNB__alpha\" : (1,0.1) }\n",
    "\n",
    "clf = GridSearchCV(pipe, parameters, scoring = \"f1_weighted\", cv = 5, refit = True)\n",
    "clf.fit(train_1[\"text\"], train_1[\"Label\"])\n",
    "print(classification_report(test_1[\"Label\"], clf.predict(test_1[\"text\"])))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0f58191c",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4d34eb9b",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "bf51f06d",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "289e17cc",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
